import { Asset } from 'expo-asset';
import { router, Stack } from 'expo-router';
import { useEffect, useState } from 'react';
import { View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { WebView } from 'react-native-webview';

import { ThemedPressable, ThemedText } from '@/components/themed';
import { useAppColorScheme } from '@/state/theme-context';
import { palette } from '@/theme/tokens';

// Bundled at build time via Metro's asset pipeline (see metro.config.js's
// assetExts) from assets/theory-book.pdf, generated by
// scripts/theory-book/generate_book.py. Reading it back offline through a
// WebView is the same approach Expo's own docs recommend for local PDFs —
// no network fetch, works from a plain file:// URI on both platforms.
const theoryBookAsset = Asset.fromModule(require('../../../assets/theory-book.pdf'));

export default function TheoryBookScreen() {
  const p = palette(useAppColorScheme().scheme);
  const [uri, setUri] = useState<string | null>(theoryBookAsset.localUri);
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    if (uri) return;
    theoryBookAsset
      .downloadAsync()
      .then((asset) => setUri(asset.localUri))
      .catch(() => setFailed(true));
  }, [uri]);

  return (
    <SafeAreaView className="flex-1" style={{ backgroundColor: p.bg }} edges={['top']}>
      <Stack.Screen options={{ headerShown: false }} />
      <View className="flex-row items-center px-6 pt-2 pb-3">
        <ThemedPressable hitSlop={8} onPress={() => router.back()}>
          <ThemedText tone="fog" className="text-small font-sans">
            ‹ Tillbaka
          </ThemedText>
        </ThemedPressable>
        <ThemedText className="text-body font-sans-semibold ml-4">Studiehandbok</ThemedText>
      </View>

      {failed ? (
        <View className="flex-1 items-center justify-center px-8">
          <ThemedText tone="fog" className="text-body font-sans text-center">
            Kunde inte öppna studiehandboken.
          </ThemedText>
        </View>
      ) : uri ? (
        <WebView source={{ uri }} style={{ flex: 1 }} originWhitelist={['*']} />
      ) : (
        <View className="flex-1 items-center justify-center">
          <ThemedText tone="fog" className="text-body font-sans">
            Laddar…
          </ThemedText>
        </View>
      )}
    </SafeAreaView>
  );
}
