import { Asset } from 'expo-asset';
import * as FileSystem from 'expo-file-system/legacy';
import { router, Stack } from 'expo-router';
import { useEffect, useState } from 'react';
import { View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import Pdf from 'react-native-pdf';

import { ThemedPressable, ThemedText } from '@/components/themed';
import { useAppColorScheme } from '@/state/theme-context';
import { palette } from '@/theme/tokens';

// Bundled at build time via Metro's asset pipeline (see metro.config.js's
// assetExts) from assets/theory-book.pdf, generated by
// scripts/theory-book/generate_book.py.
//
// Rendered with react-native-pdf rather than a WebView: Android's WebView
// does not reliably render local file:// PDFs (its PDFium viewer only
// activates for http(s)-loaded PDFs — a long-standing platform
// limitation, not something WebView props can work around), so this
// needs a real native PDF renderer instead. In a standalone build the
// bundled asset also resolves to an asset:/// URI rather than a real
// filesystem path, so it's copied out to the cache directory once first.
const theoryBookAsset = Asset.fromModule(require('../../../assets/theory-book.pdf'));
const DEST_URI = `${FileSystem.cacheDirectory ?? ''}theory-book.pdf`;

export default function TheoryBookScreen() {
  const p = palette(useAppColorScheme().scheme);
  const [uri, setUri] = useState<string | null>(null);
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    let cancelled = false;

    async function prepare() {
      try {
        await theoryBookAsset.downloadAsync();
        const source = theoryBookAsset.localUri ?? theoryBookAsset.uri;
        if (!source || !FileSystem.cacheDirectory) throw new Error('no local asset uri');

        const info = await FileSystem.getInfoAsync(DEST_URI);
        if (!info.exists) {
          await FileSystem.copyAsync({ from: source, to: DEST_URI });
        }
        if (!cancelled) setUri(DEST_URI);
      } catch {
        if (!cancelled) setFailed(true);
      }
    }

    prepare();
    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <SafeAreaView className="flex-1" style={{ backgroundColor: p.bg }} edges={['top']}>
      <Stack.Screen options={{ headerShown: false }} />
      <View className="flex-row items-center px-6 pt-2 pb-3">
        <ThemedPressable hitSlop={8} onPress={() => router.back()}>
          <ThemedText tone="fog" className="text-small font-sans">
            ‹ Tillbaka
          </ThemedText>
        </ThemedPressable>
        <ThemedText className="text-body font-sans-semibold ml-4">Studiehandbok</ThemedText>
      </View>

      {failed ? (
        <View className="flex-1 items-center justify-center px-8">
          <ThemedText tone="fog" className="text-body font-sans text-center">
            Kunde inte öppna studiehandboken.
          </ThemedText>
        </View>
      ) : uri ? (
        <Pdf
          source={{ uri }}
          style={{ flex: 1, backgroundColor: p.bg }}
          onError={() => setFailed(true)}
        />
      ) : (
        <View className="flex-1 items-center justify-center">
          <ThemedText tone="fog" className="text-body font-sans">
            Laddar…
          </ThemedText>
        </View>
      )}
    </SafeAreaView>
  );
}
